[package]
name = "minim-app"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "minim"
path = "src/main.rs"

[dependencies]
iced = { version = "0.14.0", features = ["tokio"] }
minim-config = { path = "../minim-config" }
minim-core = { path = "../minim-core" }
minim-provider = { path = "../minim-provider" }
minim-types = { path = "../minim-types" }
minim-ui = { path = "../minim-ui" }

[target.'cfg(target_os = "macos")'.dependencies]
futures-channel = "0.3"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-foundation = "0.3"
